### PR TITLE
Stale axis fix

### LINKED ISSUE #220: Stale axes when growth=True and fill changes an axis
Currently, the axes seem to be copies. They should not be.

### PR DESCRIPTION
**Pull request by henryiii**
Needs tests, but I think I've fixed #220.

### CODE REVIEW

File: include/boost/histogram/python/register_histogram.hpp [hunk 1]
```diff
@@ -171,16 +171,25 @@ register_histogram(py::module& m, const char* name, const char* desc) {
...
         .def(
             "axis",
-            [](const histogram_t& self, int i) {
+            [](const histogram_t& self, int i) -> py::object {
                 unsigned ii = i < 0 ? self.rank() - (unsigned)std::abs(i) : (unsigned)i;
-                if(ii < self.rank())
-                    return self.axis(ii);
+
+                if(ii < self.rank()) {
+                    const axis_variant& var = bh::unsafe_access::axis(self, ii);
```
Comment (HDembinski) [inline include/boost/histogram/python/register_histogram.hpp]: this is basically what i had in mind as well. only a minor comment: why use unsafe_access here instead of `self.axis(ii)`?

Comment (HDembinski) [reply include/boost/histogram/python/register_histogram.hpp]: apart from that this looks very good

Comment (henryiii) [reply include/boost/histogram/python/register_histogram.hpp]: Leftover from when I first tried to avoid const, since the py::cast is going to ignore the const. Fixed.

File: tests/test_histogram.py [hunk 2]
```diff
@@ -815,3 +816,50 @@ def test_fill_with_sequence_4():
...
+
+
+def test_axes_lifetime():
+    h = bh.Histogram(bh.axis.Regular(10, 0, 1, metadata=2))
+
+    ax = h.axes[0]
+
+    # 2 is the minimum refcount, so the *python* object should be deleted
+    # after the del; hopefully the C++ object lives through the axis instance.
+    assert sys.getrefcount(h) == 2
```
Comment (henryiii) [inline tests/test_histogram.py]: This being 2 is a little worrisome, hopefully keepalive is working here.
